### ISSUE TITLE
update_init_params in reptile_rl.py

### ISSUE THREAD

**Issue by hccz95** [finninmunich/Maml-Reptile-RL#1]
Hi!
I have a question about your code.
In line 107 of `reptile_rl.py`, the temp_params is updated by `temp_params += step_size * (target_params - temp_params)`.
However, according to the pseudocode in the original paper of reptile, the updating may be written by `temp_params += step_size * (target_params - init_params)`.

I wonder is this your intentional modification? What effects can it brings?

**Comment by finninmunich** [comment]
Hi, I check the original paper and I think the pseudocode also means `temp_params += step_size * (target_params - temp_params)` (on the first iteration is `temp_params += step_size * (target_params - init_params)`, but at the beginning `temp_params = init_params`)
An image to explain Reptile: 
![reptile](https://user-images.githubusercontent.com/75730191/171845255-ca28d774-4e32-4177-81f9-7f2bfe4b2263.png)

**Comment by hccz95** [comment]
I think your picture corresponds  to the serial version of Reptile.
If we intent to implement the serial version like your picture, line 100 in `reptile.py` has to be changed to `model.network.load_state_dict(temp_params)`

In my opinion, the serial and batch version of Reptile are following:

Serial version of Reptile:
```
init_params, temp_params = model.parameters()
for task in task_set:
    model.load(temp_params)
    target_params = model.learn()
    temp_params += step_size * (target_params - temp_params)
model.load(temp_params)
```

Batch version of Reptile:
```
init_params, temp_params = model.parameters()
for task in task_set:
    model.load(init_params)
    target_params = model.learn()
    temp_params += step_size * (target_params - init_params)
model.load(temp_params)
```

**Comment by finninmunich** [comment]
You are right, the code on line 100 should be changed because I wanted to implement a serial version, thanks for pointing this out 😄 I think I introduced a bug when I created this repo.
