### ISSUE TITLE
FileNotFoundError when attempting to run 'evaluation.py'

### ISSUE THREAD

**Issue by babyrabbit030** [finninmunich/Maml-Reptile-RL#2]
Hello,

I've been trying to run your MAML algorithm but have run into some difficulties. I'm encountering an issue during the testing portion of the 'main.py' script, specifically with 'evaluation.py'.

The snippet of the code causing the problem is as follows:
if normalization:
    mean = np.load('obs_mean.npy')
    std = np.load('obs_std.npy')
total_ep_ret = 0

The error message I receive is:
FileNotFoundError: [Errno 2] No such file or directory: 'obs_mean.npy'

I have tried to locate 'obs_mean.npy' and 'obs_std.npy', but I haven't been able to find them in the repository. If you could either provide these files or guide me on how I might generate them myself, I would greatly appreciate it. I believe these files are essential for the successful operation of the MAML code.

Thank you for your help and I look forward to your response.

My email address is [13939930146@163.com](mailto:13939930146@163.com). I appreciate your assistance with this matter, and look forward to hearing from you soon.

**Comment by finninmunich** [comment]
Hi, you have to generate the mean and std by yourself during training :)

To be honest, I think I deleted the part of normalization because I found out that adding normalizaiton to training won't improve the performance of our agents.

Maybe you can just delete this normalization part.
