### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by dbdxyuyi** [finninmunich/Maml-Reptile-RL#3]
你好，我对你的reptile我复现的时候遇到问题，请问能不能公布下你使用python包的版本号

**Comment by finninmunich** [comment]
应该是3.8

**Comment by dbdxyuyi** [comment]
![微信图片_20240223100814](https://github.com/finninmunich/Maml-Reptile-RL/assets/99106823/41cac526-b0f7-41c9-a3f1-a16824c10770)
我想问一下，你的强化学习环境是怎么安装的，我一直安装不成功

**Comment by dbdxyuyi** [comment]
![微信图片_20240223102113](https://github.com/finninmunich/Maml-Reptile-RL/assets/99106823/2e24679d-dbbc-4d65-ba82-2697b55b1ccd)
我把pybulletgym从pybullet-gym里面复制出来，不知道这样做是否正确，但是又遇到了这个问题

**Comment by finninmunich** [comment]
> ![微信图片_20240223102113](https://private-user-images.githubusercontent.com/99106823/307207481-2e24679d-dbbc-4d65-ba82-2697b55b1ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTYxOTAsIm5iZiI6MTcwODY1NTg5MCwicGF0aCI6Ii85OTEwNjgyMy8zMDcyMDc0ODEtMmUyNDY3OWQtZGJiYy00ZDY1LWJhODItMjY5N2I1NWIxY2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyMzgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MjE0NWY2NTZjYmExNDA0YzdjMDliZmEwZTU5NDIwYTU4MTkzN2Y5NGQ3MThmZGE3OGE1OTc3N2U4MmI5M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ltBCo2OHYA6XmKyi5jAsWGzKDwyl1KzskcJW2dgRZns) 我把pybulletgym从pybullet-gym里面复制出来，不知道这样做是否正确，但是又遇到了这个问题

你可以先通过官方的instruction安装pybulletgym，然后可以按照我post的代码去修改。
具体来说，修改的代码其实只是将一些环境中可以修改的参数提取出来，作为不同env的setup

**Comment by finninmunich** [comment]
> ![微信图片_20240223102113](https://private-user-images.githubusercontent.com/99106823/307207481-2e24679d-dbbc-4d65-ba82-2697b55b1ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTYzNDEsIm5iZiI6MTcwODY1NjA0MSwicGF0aCI6Ii85OTEwNjgyMy8zMDcyMDc0ODEtMmUyNDY3OWQtZGJiYy00ZDY1LWJhODItMjY5N2I1NWIxY2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyNDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYWU2MWE5OTU0ZDUyNGQwOGMxMDZmMTFlMWE1NTI0ZGRjMmIxMzVmNWM1ODQ1YzJjNmI2MmM1MmMyYTc4ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fy0f74lPPHfpLeXp4347QPAzD4e6wSiod8kbWh3xapI) 我把pybulletgym从pybullet-gym里面复制出来，不知道这样做是否正确，但是又遇到了这个问题

你也可以根据代码中pybulletgym的setup.py来安装这个库，但我不确定它是否可行
